#!/usr/bin/env bash
set -o errexit

run_arg="${1:-test}"
case "${run_arg}" in
"test")
    yarn
    yarn test:unit
    yarn test:integration
    ;;
"start")
    yarn start
    ;;
 "ci")
    yarn
    sudo npm install -g typescript
    tsc --noEmit
    yarn test:unit
    ./deploy.sh
    ;;
 *)
   echo "Unexpected argument given:" $1
esac
