#!/usr/bin/env bash
set -o errexit

export NVM_DIR=$HOME/.nvm

if [[ ! -d ${NVM_DIR} ]]; then
  mkdir -p ${NVM_DIR}
  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
fi

if [[ ! $(command -v nvm) ]]; then
  set +e
  [[ -s "$NVM_DIR/nvm.sh" ]] && \. "$NVM_DIR/nvm.sh"
  set -e
fi

nvm install

if [[ ! $(command -v yarn) ]]; then
    npm install -g yarn
fi


run_arg="${1:-test}"
case "${run_arg}" in
"test")
    yarn
    yarn test:unit
    yarn test:integration
    ;;
"start")
    yarn start
    ;;
 "ci")
    yarn
    sudo npm install -g typescript
    tsc --noEmit
    yarn test:unit
    ./deploy.sh
    ;;
 *)
   echo "Unexpected argument given:" $1
esac
