# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  build_deploy:
    steps:
      - checkout
      - run:
          name: build & deploy
          command: |
            ./run ci

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_deploy:
          filters:
            branches:
              only: master